brain_two/brain_two/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todos/', include('todos.urls', namespace='todos')),
]

brain_two/todos/urls.py
from django.urls import path
from .views import todo_list_view, todo_list_detail_view, todo_list_update_view
from . import views

app_name = 'todos'
urlpatterns = [
    path('', todo_list_view, name='todo_list_list'),
    path('<int:id>/', todo_list_detail_view, name='todo_list_detail'),
    path('create/', views.todo_list_create_view, name='todo_list_create'),
    path('<int:id>/edit/', todo_list_update_view, name='todo_list_update'),
]

brain_two/todos/models.py
from django.db import models
from django.utils import timezone

class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(default=timezone.now)
    
    def __str__(self):
        return self.name

class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateTimeField(null=True, blank=True)
    is_completed = models.BooleanField(default=False)
    list = models.ForeignKey(
        TodoList,
        on_delete=models.CASCADE,
        related_name='items'
    )
    
    def __str__(self):
        return self.task

brain_two/todos/forms.py
from django import forms
from .models import TodoList

class TodoListForm(forms.ModelForm):
    class Meta:
        model = TodoList
        fields = ['name']

brain_two/todos/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import TodoList
from .forms import TodoListForm

def todo_list_view(request):
    todo_lists = TodoList.objects.all()
    context = {'todo_lists': todo_lists}
    return render(request, 'todos/todo_list.html', context)

def todo_list_detail_view(request, id):
    todo_list = get_object_or_404(TodoList, id=id)
    context = {'todo_list': todo_list}
    return render(request, 'todos/todo_list_detail.html', context)

def todo_list_create_view(request):
    if request.method == 'POST':
        form = TodoListForm(request.POST)
        if form.is_valid():
            todo_list = form.save()
            return redirect('todos:todo_list_detail', id=todo_list.id)
    else:
        form = TodoListForm()
    context = {'form': form}
    return render(request, 'todos/todo_list_create.html', context)

def todo_list_update_view(request, id):
    todo_list = get_object_or_404(TodoList, id=id)
    if request.method == 'POST':
        form = TodoListForm(request.POST, instance=todo_list)
        if form.is_valid():
            form.save()
            return redirect('todos:todo_list_detail', id=id)
    else:
        form = TodoListForm(instance=todo_list)
    context = {'form': form}
    return render(request, 'todos/todo_list_update.html', context)

brain_two/todos/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>My Project</title>
    </head>

    <body>
    {% block content %}{% endblock content %}
    </body>
</html>

brain_two/todos/templates/todos/todo_list.html
{% extends 'base.html' %}

{% block content %}
  <main>
    <div>
      <h1>My Lists</h1>
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Number of items</th>
          </tr>
        </thead>
        <tbody>
          {% for todo_list in todo_lists %}
            <tr>
              <td><a href="{% url 'todos:todo_list_detail' todo_list.id %}">{{ todo_list.name }}</a></td>
              <td>{{ todo_list.items.count }}</td>
              <a href="{% url 'todos:todo_list_create' %}">Create a New Todo List</a>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </main>
{% endblock %}

brain_two/todos/templates/todos/todo_list_create.html
{% extends 'base.html' %}

{% block content %}
  <main>
    <div>
      <h1>Create a New List</h1>
      <form method="post">
        {% csrf_token %}
        <input type="text" name="name" required>
        <button type="submit">Create</button>
      </form>
    </div>
  </main>
{% endblock %}

brain_two/todos/templates/todos/todo_list_detail.html
{% extends 'base.html' %}

{% block content %}
  <main>
    <div>
      <h1>{{ todo_list.name }}</h1>
      <p><a href="{% url 'todos:todo_list_update' todo_list.id %}">Edit</a></p>
      <h2>Tasks</h2>
      <table>
        <thead>
          <tr>
            <th>Task</th>
            <th>Due date</th>
          </tr>
        </thead>
        <tbody>
          {% for task in todo_list.tasks.all %}
            <tr>
              <td>{{ task.title }}</td>
              <td>{{ task.due_date }}</td>
            </tr>
          {% empty %}
            <tr>
              <td colspan="2">No tasks found.</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </main>
{% endblock %}

brain_two/todos/templates/todos/todo_list_update.html
{% extends 'base.html' %}

{% block content %}
  <main>
    <div>
      <h1>Update list</h1>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update</button>
      </form>
    </div>
  </main>
{% endblock %}